name: Deploy PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build pdf from tex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          
      - name: Ensure output directory exists
        run: mkdir -p output
        
      - name: Copy
        run: cp ./cv.pdf ./output/cv.pdf
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv.pdf
          path: output/cv.pdf

      - name: Deploy
        run: |
          git config --global user.name 'federicomarrabot'
          git config --global user.email 'bot@noreply.federicomarra.com'
          git checkout main
          git add output/cv.pdf
          git commit -m 'Deploy cv.pdf to output folder'
          git push origin main
