name: Curriculum & Resumé PDFs

on:
  push:
    branches: [ main ]
    paths:
      - 'cv-sec/**'
      - '.github/workflows/build-latex-cv-resume.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'cv-sec/**'
      - '.github/workflows/build-latex-cv-resume.yml'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y inkscape texlive-xetex texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

      - name: Build cv.pdf from cv.tex
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex
          compiler: xelatex
          extra_fonts: ./fonts/*.ttf
          texlive_version: 2024

      - name: Build resume.pdf from resume.tex
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
          compiler: xelatex
          extra_fonts: ./fonts/*.ttf
          texlive_version: 2024
          
      - name: Ensure output directory exists
        run: mkdir -p output

      - name: Move cv pdf
        run: cp ./cv.pdf ./output/cv.pdf
	
      - name: Move resume pdf
        run:  cp ./resume.pdf ./output/resume.pdf

      - name: Upload cv.pdf Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv.pdf
          path: output/cv.pdf

      - name: Upload resume.pdf Artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume.pdf
          path: output/resume.pdf

      - name: Deploy
        run: |
          git config --global user.name 'federicomarra'
          git config --global user.email 'fecrom@gmail.com'
          git checkout main
          git add output/cv.pdf output/resume.pdf
          git commit -m 'Compile Curriculum & Resumé PDFs in output folder'
          git push origin main
