name: Deploy PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
      - name: Copy
        run: |
          mkdir output
          cp ./cv.pdf ./output/cv.pdf
      - uses: actions/upload-artifact@v3
        with:
          name: thesis
          path: output/cv.pdf
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          CLEAN: true
          SINGLE_COMMIT: true
          FOLDER: output
          GIT_CONFIG_NAME: federicomarrabot
          GIT_CONFIG_EMAIL: bot@noreply.federicomarra.com
